fnndsc.babymri.org:
  image: fnndsc/fnndsc.babymri.org
  ports:
    - "8060:8060"
  volumes:
   - .:/home/fnndsc/src
   - /home/fnndsc/src/bower_components
  labels:
    name: "FNNDSC Web App"
    role: "FNNDSC Web App development server"
